# Configuraci�n del servidor
server.port=8080

# Configuraci�n de H2 en memoria
spring.datasource.url=jdbc:h2:mem:helpdeskdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=copixto
spring.datasource.password=

# Propiedades de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar consola web de H2 para depuraci�n r�pida
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jdbc:h2:mem:helpdeskdb